// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProfileRole string

const (
	ProfileRoleADMIN ProfileRole = "ADMIN"
	ProfileRoleUSER  ProfileRole = "USER"
)

func (e *ProfileRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProfileRole(s)
	case string:
		*e = ProfileRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProfileRole: %T", src)
	}
	return nil
}

type NullProfileRole struct {
	ProfileRole ProfileRole
	Valid       bool // Valid is true if ProfileRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProfileRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProfileRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProfileRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProfileRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProfileRole), nil
}

func (e ProfileRole) Valid() bool {
	switch e {
	case ProfileRoleADMIN,
		ProfileRoleUSER:
		return true
	}
	return false
}

func AllProfileRoleValues() []ProfileRole {
	return []ProfileRole{
		ProfileRoleADMIN,
		ProfileRoleUSER,
	}
}

type Profile struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	OidcSub     string
	Roles       []ProfileRole
	AvatarUrl   *string
	DisplayName *string
	Bio         *string
}

type Upload struct {
	ID               int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Filepath         string
	OriginalFilename string
	Extension        string
	Size             int32
	Mimetype         string
	UploaderIp       string
}
