// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlc

import (
	"context"
)

const countProfiles = `-- name: CountProfiles :one
SELECT count(*) FROM profiles
`

func (q *Queries) CountProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (oidc_sub)
VALUES ($1)
RETURNING id, created_at, updated_at, oidc_sub, roles, avatar_url, display_name, bio
`

func (q *Queries) CreateProfile(ctx context.Context, oidcSub string) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, oidcSub)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcSub,
		&i.Roles,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.Bio,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, created_at, updated_at, oidc_sub, roles, avatar_url, display_name, bio FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id int32) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcSub,
		&i.Roles,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.Bio,
	)
	return i, err
}

const getProfileByOIDCSub = `-- name: GetProfileByOIDCSub :one
SELECT id, created_at, updated_at, oidc_sub, roles, avatar_url, display_name, bio FROM profiles WHERE oidc_sub = $1
`

func (q *Queries) GetProfileByOIDCSub(ctx context.Context, oidcSub string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByOIDCSub, oidcSub)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcSub,
		&i.Roles,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.Bio,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    avatar_url   = COALESCE($1, avatar_url),
    display_name = COALESCE($2, display_name),
    bio          = COALESCE($3, bio)
WHERE id = $4
RETURNING id, created_at, updated_at, oidc_sub, roles, avatar_url, display_name, bio
`

type UpdateProfileParams struct {
	AvatarUrl   *string
	DisplayName *string
	Bio         *string
	ID          int32
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.AvatarUrl,
		arg.DisplayName,
		arg.Bio,
		arg.ID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OidcSub,
		&i.Roles,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.Bio,
	)
	return i, err
}
