// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload.sql

package sqlc

import (
	"context"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (
    filepath, original_filename, extension, size, mimetype, uploader_ip, uploader_profile_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, created_at, updated_at, filepath, original_filename, extension, size, mimetype, uploader_ip, uploader_profile_id
`

type CreateUploadParams struct {
	Filepath          string
	OriginalFilename  string
	Extension         string
	Size              int32
	Mimetype          string
	UploaderIp        string
	UploaderProfileID *int32
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.Filepath,
		arg.OriginalFilename,
		arg.Extension,
		arg.Size,
		arg.Mimetype,
		arg.UploaderIp,
		arg.UploaderProfileID,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Filepath,
		&i.OriginalFilename,
		&i.Extension,
		&i.Size,
		&i.Mimetype,
		&i.UploaderIp,
		&i.UploaderProfileID,
	)
	return i, err
}

const getUploadByFilepath = `-- name: GetUploadByFilepath :one
SELECT id, created_at, updated_at, filepath, original_filename, extension, size, mimetype, uploader_ip, uploader_profile_id FROM uploads WHERE filepath = $1
`

func (q *Queries) GetUploadByFilepath(ctx context.Context, filepath string) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadByFilepath, filepath)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Filepath,
		&i.OriginalFilename,
		&i.Extension,
		&i.Size,
		&i.Mimetype,
		&i.UploaderIp,
		&i.UploaderProfileID,
	)
	return i, err
}
