package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"errors"
	"runtime"
	"time"

	"github.com/uxname/liteend-go/internal/auth"
	"github.com/uxname/liteend-go/internal/db/sqlc"
	"github.com/uxname/liteend-go/internal/graph/generated"
	"github.com/uxname/liteend-go/internal/graph/model"
	"github.com/uxname/liteend-go/internal/profile"
	"github.com/uxname/liteend-go/internal/version"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.ProfileUpdateInput) (*model.Profile, error) {
	user, err := auth.Require(ctx)
	if err != nil {
		return nil, err
	}
	if err := validateProfileUpdate(input); err != nil {
		return nil, err
	}
	updated, err := r.Profiles.Update(ctx, user.ID, user.OidcSub, profile.UpdateParams{
		AvatarURL:   input.AvatarURL,
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
	})
	if err != nil {
		return nil, err
	}
	if r.PubSub != nil {
		if err := r.PubSub.Publish(ctx, updated); err != nil {
			r.Log.Warn("publish profileUpdated failed", "error", err)
		}
	}
	return toModelProfile(updated), nil
}

// AddTestJob is the resolver for the addTestJob field.
func (r *mutationResolver) AddTestJob(ctx context.Context, message string) (bool, error) {
	if _, err := auth.Require(ctx); err != nil {
		return false, err
	}
	if r.Queue == nil {
		return false, errors.New("service unavailable")
	}
	if err := r.Queue.AddTestJob(ctx, message); err != nil {
		return false, err
	}
	return true, nil
}

// Echo is the resolver for the echo field (ADMIN only).
func (r *mutationResolver) Echo(ctx context.Context, text string) (string, error) {
	if _, err := auth.RequireRole(ctx, sqlc.ProfileRoleADMIN); err != nil {
		return "", err
	}
	return text, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Profile, error) {
	user, err := auth.Require(ctx)
	if err != nil {
		return nil, err
	}
	return toModelProfile(*user), nil
}

// TestTranslation is the resolver for the testTranslation field (ADMIN only).
func (r *queryResolver) TestTranslation(ctx context.Context, username string) (string, error) {
	if _, err := auth.RequireRole(ctx, sqlc.ProfileRoleADMIN); err != nil {
		return "", err
	}
	if r.I18n == nil {
		return "", errors.New("service unavailable")
	}
	return r.I18n.Translate(ctx, "hello", map[string]string{"username": username}), nil
}

// Echo is the resolver for the echo field (ADMIN only).
func (r *queryResolver) Echo(ctx context.Context, text string) (string, error) {
	if _, err := auth.RequireRole(ctx, sqlc.ProfileRoleADMIN); err != nil {
		return "", err
	}
	return text, nil
}

// Debug is the resolver for the debug field (ADMIN only).
func (r *queryResolver) Debug(ctx context.Context) (map[string]any, error) {
	requester, err := auth.RequireRole(ctx, sqlc.ProfileRoleADMIN)
	if err != nil {
		return nil, err
	}

	var mem runtime.MemStats
	runtime.ReadMemStats(&mem)

	total, err := r.Profiles.Count(ctx)
	if err != nil {
		return nil, err
	}

	return map[string]any{
		"serverTime": time.Now().UTC().Format(time.RFC3339),
		"uptime":     time.Since(startTime).Seconds(),
		"appInfo":    version.Get(),
		"memory": map[string]uint64{
			"alloc":      mem.Alloc,
			"totalAlloc": mem.TotalAlloc,
			"sys":        mem.Sys,
			"heapAlloc":  mem.HeapAlloc,
		},
		"totalUsers": total,
		"requester": map[string]any{
			"id":      requester.ID,
			"oidcSub": requester.OidcSub,
			"roles":   requester.Roles,
		},
	}, nil
}

// ProfileUpdated is the resolver for the profileUpdated field.
func (r *subscriptionResolver) ProfileUpdated(ctx context.Context) (<-chan *model.Profile, error) {
	user, err := auth.Require(ctx)
	if err != nil {
		return nil, err
	}
	if r.PubSub == nil {
		return nil, errors.New("service unavailable")
	}

	src := r.PubSub.SubscribeForUser(ctx, user.ID)
	out := make(chan *model.Profile, 1)
	go func() {
		defer close(out)
		defer func() {
			if rec := recover(); rec != nil {
				r.Log.Error("profileUpdated subscription bridge panicked", "panic", rec)
			}
		}()
		for p := range src {
			select {
			case out <- toModelProfile(p):
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
