// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/uxname/liteend-go/internal/db/sqlc"
)

type Mutation struct {
}

type Profile struct {
	ID          string             `json:"id"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
	OidcSub     string             `json:"oidcSub"`
	Roles       []sqlc.ProfileRole `json:"roles"`
	AvatarURL   *string            `json:"avatarUrl,omitempty"`
	DisplayName *string            `json:"displayName,omitempty"`
	Bio         *string            `json:"bio,omitempty"`
}

type ProfileUpdateInput struct {
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Bio         *string `json:"bio,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
